In [5]:
import pandas as pd
df = pd.read_csv("cleaned_supply_chain_data.csv")

In [10]:
df.columns

Index(['Product type', 'SKU', 'Price', 'Availability',
       'Number of products sold', 'Revenue generated', 'Customer demographics',
       'Stock levels', 'Lead times', 'Order quantities', 'Shipping times',
       'Shipping carriers', 'Shipping costs', 'Supplier name', 'Location',
       'Lead time', 'Production volumes', 'Manufacturing lead time',
       'Manufacturing costs', 'Inspection results', 'Defect rates',
       'Transportation modes', 'Routes', 'Costs'],
      dtype='object')

In [11]:
df.select_dtypes(include="number").columns

Index(['Price', 'Availability', 'Number of products sold', 'Revenue generated',
       'Stock levels', 'Lead times', 'Order quantities', 'Shipping times',
       'Shipping costs', 'Lead time', 'Production volumes',
       'Manufacturing lead time', 'Manufacturing costs', 'Defect rates',
       'Costs'],
      dtype='object')

In [14]:
df["Total Cost"] = df["Shipping costs"] + df["Manufacturing costs"]

In [15]:
df["Revenue per Product"] = df["Revenue generated"] / df["Number of products sold"]

In [16]:
df["Cost per Product"] = df["Total Cost"] / df["Number of products sold"]

In [17]:
df["Estimated Profit"] = df["Revenue generated"] - df["Total Cost"]

In [18]:
df["Profit Margin"] = (df["Estimated Profit"] / df["Revenue generated"]) * 100

In [19]:
df[[
    "Total Cost",
    "Revenue per Product",
    "Cost per Product",
    "Estimated Profit",
    "Profit Margin"
]].head()

,Total Cost,Revenue per Product,Cost per Product,Estimated Profit,Profit Margin
0,49.236451,10.800495,0.061392,8612.760341,99.431581
1,43.333344,10.137092,0.058877,7417.566722,99.419194
2,38.742499,1197.218703,4.842812,9539.007127,99.595495
3,37.354310,93.576342,0.450052,7729.482116,99.519054
4,95.955709,3.084392,0.110167,2590.549443,96.428233

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 29 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Product type             100 non-null    object
 1   SKU                      100 non-null    object
 2   Price                    100 non-null    float64
 3   Availability             100 non-null    int64
 4   Number of products sold  100 non-null    int64
 5   Revenue generated        100 non-null    float64
 6   Customer demographics    100 non-null    object
 7   Stock levels             100 non-null    int64
 8   Lead times               100 non-null    int64
 9   Order quantities         100 non-null    int64
 10  Shipping times           100 non-null    int64
 11  Shipping carriers        100 non-null    object
 12  Shipping costs           100 non-null    float64
 13  Supplier name            100 non-null    object
 14  Location                 100 non-null    object
 15  Lead time                100 non-null    int64
 16  Production volumes       100 non-null    int64
 17  Manufacturing lead time  100 non-null    int64
 18  Manufacturing costs      100 non-null    float64
 19  Inspection results       100 non-null    object
 20  Defect rates             100 non-null    float64
 21  Transportation modes     100 non-null    object
 22  Routes                   100 non-null    object
 23  Costs                    100 non-null    float64
 24  Total Cost               100 non-null    float64
 25  Revenue per Product      100 non-null    float64
 26  Cost per Product         100 non-null    float64
 27  Estimated Profit         100 non-null    float64
 28  Profit Margin            100 non-null    float64
dtypes: float64(11), int64(9), object(9)
memory usage: 22.8+ KB

In [21]:
df.describe()

,Price,Availability,Number of products sold,Revenue generated,Stock levels,Lead times,Order quantities,Shipping times,Shipping costs,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Defect rates,Costs,Total Cost,Revenue per Product,Cost per Product,Estimated Profit,Profit Margin
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,49.462461,48.400000,460.990000,5776.048187,47.770000,15.960000,49.220000,5.750000,5.548149,17.080000,567.840000,14.77000,47.266693,2.277158,529.245782,52.814842,41.356314,0.298431,5723.233345,98.622649
std,31.168193,30.743317,303.780074,2732.841744,31.369372,8.785801,26.784429,2.724283,2.651376,8.846251,263.046861,8.91243,28.982841,1.461366,258.301696,29.119658,128.153396,0.645369,2739.385370,1.387700
min,1.699976,1.000000,8.000000,1061.618523,0.000000,1.000000,1.000000,1.000000,1.013487,1.000000,104.000000,1.00000,1.085069,0.018608,103.916248,4.965832,1.366235,0.007683,1052.424038,93.813937
25%,19.597823,22.750000,184.250000,2812.847151,16.750000,8.000000,26.000000,3.750000,3.540248,10.000000,352.000000,7.00000,22.983299,1.009650,318.778455,29.656465,7.788644,0.060763,2751.791865,98.170341
50%,51.239831,43.500000,392.500000,6006.352023,47.500000,17.000000,52.000000,6.000000,5.320534,18.000000,568.500000,14.00000,45.905622,2.141863,520.430444,49.928521,12.828546,0.105294,5958.072985,99.092837
75%,77.198228,75.000000,704.250000,8253.976921,73.000000,24.000000,71.250000,8.000000,7.601695,25.000000,797.000000,23.00000,68.621026,3.563995,763.078231,76.282502,23.435046,0.292834,8178.860299,99.486304
max,99.171329,100.000000,996.000000,9866.465458,100.000000,30.000000,96.000000,10.000000,9.929816,30.000000,985.000000,30.00000,99.466109,4.939255,997.413450,107.366333,1197.218703,4.842812,9847.492129,99.936527

In [22]:
df["Sales Efficiency"] = (
    df["Number of products sold"] / df["Production volumes"]
)

In [23]:
df["Inventory Turnover"] = (
    df["Number of products sold"] / df["Stock levels"]
)

In [24]:
df["Order Fulfillment Ratio"] = (
    df["Number of products sold"] / df["Order quantities"]
)

In [25]:
df["Shipping Delay"] = df["Shipping times"] - df["Lead times"]

In [26]:
df["Estimated Defect Quantity"] = (
    df["Production volumes"] * df["Defect rates"] / 100
)

In [27]:
df["Cost Percentage"] = (
    df["Total Cost"] / df["Revenue generated"]
) * 100

In [28]:
new_features = [
    "Total Cost",
    "Revenue per Product",
    "Cost per Product",
    "Estimated Profit",
    "Profit Margin",
    "Sales Efficiency",
    "Inventory Turnover",
    "Order Fulfillment Ratio",
    "Shipping Delay",
    "Estimated Defect Quantity",
    "Cost Percentage"
]

df[new_features].head()

,Total Cost,Revenue per Product,Cost per Product,Estimated Profit,Profit Margin,Sales Efficiency,Inventory Turnover,Order Fulfillment Ratio,Shipping Delay,Estimated Defect Quantity,Cost Percentage
0,49.236451,10.800495,0.061392,8612.760341,99.431581,3.730233,13.827586,8.354167,-3,0.486782,0.568419
1,43.333344,10.137092,0.058877,7417.566722,99.419194,1.423598,13.886792,19.891892,-28,25.095532,0.580806
2,38.742499,1197.218703,4.842812,9539.007127,99.595495,0.008239,8.000000,0.090909,-8,44.477554,0.404505
3,37.354310,93.576342,0.450052,7729.482116,99.519054,0.088581,3.608696,1.406780,-7,44.476098,0.480946
4,95.955709,3.084392,0.110167,2590.549443,96.428233,2.103865,174.200000,15.553571,5,13.022699,3.571767

In [29]:
import numpy as np

df.replace([np.inf, -np.inf], np.nan, inplace=True)

df[new_features].isnull().sum()

Total Cost                   0
Revenue per Product          0
Cost per Product             0
Estimated Profit             0
Profit Margin                0
Sales Efficiency             0
Inventory Turnover           1
Order Fulfillment Ratio      0
Shipping Delay               0
Estimated Defect Quantity    0
Cost Percentage              0
dtype: int64

In [30]:
df[new_features].describe()

,Total Cost,Revenue per Product,Cost per Product,Estimated Profit,Profit Margin,Sales Efficiency,Inventory Turnover,Order Fulfillment Ratio,Shipping Delay,Estimated Defect Quantity,Cost Percentage
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,99.000000,100.000000,100.000000,100.000000,100.000000
mean,52.814842,41.356314,0.298431,5723.233345,98.622649,1.028426,28.883725,25.533775,-10.210000,13.382926,1.377351
std,29.119658,128.153396,0.645369,2739.385370,1.387700,0.906883,70.769853,91.982184,9.315237,11.405597,1.387700
min,4.965832,1.366235,0.007683,1052.424038,93.813937,0.008239,0.258065,0.090909,-28.000000,0.076635,0.063473
25%,29.656465,7.788644,0.060763,2751.791865,98.170341,0.378745,4.568100,4.326471,-18.000000,3.639662,0.513696
50%,49.928521,12.828546,0.105294,5958.072985,99.092837,0.825142,8.687500,8.566776,-11.000000,11.708447,0.907163
75%,76.282502,23.435046,0.292834,8178.860299,99.486304,1.257766,19.974383,18.019608,-2.000000,20.287768,1.829659
max,107.366333,1197.218703,4.842812,9847.492129,99.936527,4.425121,602.000000,904.000000,9.000000,44.477554,6.186063

In [31]:
df.to_csv("feature_engineered_supply_chain_data.csv", index=False)